IMX_OPENGL_PKGCONFIGS_REMOVE        = ""
IMX_OPENGL_PKGCONFIGS_REMOVE:imxgpu = "glamor"
OPENGL_PKGCONFIGS:remove_mx6        = "${IMX_OPENGL_PKGCONFIGS_REMOVE}"
OPENGL_PKGCONFIGS:remove_mx7        = "${IMX_OPENGL_PKGCONFIGS_REMOVE}"
OPENGL_PKGCONFIGS:remove_mx8        = "${IMX_OPENGL_PKGCONFIGS_REMOVE}"

FILESEXTRAPATHS:prepend := "${THISDIR}/${BPN}:"
SRC_URI:append_imxgpu2d = " file://0003-Remove-check-for-useSIGIO-option.patch"
